OUTPUT_DIR: "output"
MODEL: "mvmppe"
GPUS: "0"
WORKERS: 8
PRINT_FREQ: 5

CUDNN:
    BENCHMARK: true
    DETERMINISTIC: false
    ENABLED: true

NETWORK:
    NUM_JOINTS: 17
    HIDDEN_SIZE: 128
    SOFTARGMAX_KERNEL_SIZE: 16

DATASET:
    ROOT: "data/Campus"
    TRAIN_DATASET: "campus_synthetic"
    TRAIN_SUBSET: "train"
    TEST_DATASET: "campus"
    TEST_SUBSET: "validation"
    DATA_AUGMENTATION: true
    PERTURB_SIGMA: 1.0
    SYNTHESIS_X_RANGE:
        - -2500.0
        - 8500.0
    SYNTHESIS_Y_RANGE:
        - -1000.0
        - 10000.0

TRAIN:
    BATCH_SIZE: 64
    SHUFFLE: true
    LR: 0.0001
    BEGIN_EPOCH: 0
    END_EPOCH: 100
    STEP_PER_EPOCH: 100

TEST:
    BATCH_SIZE: 64
    USE_PRED_CONFIDENCE: true
    NMS_THRESHOLD: 50

MULTI_PERSON:
    MAX_NUM_PERSONS: 5
    POSE_MIN_DEPTH: 2000.0
    POSE_MAX_DEPTH: 20000.0
    POSE_NUM_DEPTH_LAYERS: 64
    JOINT_MIN_DEPTH: -1000.0
    JOINT_MAX_DEPTH: 1000.0
    JOINT_NUM_DEPTH_LAYERS: 64
    POSE_SIGMA: 10.0
    JOINT_SIGMA: 2.0
