OUTPUT_DIR: "output"
MODEL: "mvmppe"
GPUS: "0"
WORKERS: 8
PRINT_FREQ: 5

CUDNN:
    BENCHMARK: true
    DETERMINISTIC: false
    ENABLED: true

NETWORK:
    NUM_JOINTS: 13
    HIDDEN_SIZE: 128
    SOFTARGMAX_KERNEL_SIZE: 16

DATASET:
    ROOT: "data/Panoptic"
    TRAIN_DATASET: "panoptic"
    TRAIN_SUBSET: "train"
    TEST_DATASET: "panoptic"
    TEST_SUBSET: "validation"

TRAIN:
    BATCH_SIZE: 64
    SHUFFLE: true
    LR: 0.0001
    BEGIN_EPOCH: 0
    END_EPOCH: 100
    STEP_PER_EPOCH: 500

TEST:
    BATCH_SIZE: 64
    USE_PRED_CONFIDENCE: true
    NMS_THRESHOLD: 250

MULTI_PERSON:
    MAX_NUM_PERSONS: 10
    POSE_MIN_DEPTH: 100.0
    POSE_MAX_DEPTH: 8000.0
    POSE_NUM_DEPTH_LAYERS: 64
    JOINT_MIN_DEPTH: -1000.0
    JOINT_MAX_DEPTH: 1000.0
    JOINT_NUM_DEPTH_LAYERS: 64
    POSE_SIGMA: 10.0
    JOINT_SIGMA: 15.0
